version: "3.8"
services:
  postgres:
    image: postgres:17.5
    restart: always
    container_name: local_pgdb
    ports:
      - ${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/

  redis:
    image: redis:8.0
    restart: always
    ports:
      - ${REDIS_PORT}
    env_file:
      - .env
    volumes:
      - ./data/redis/data:/root/redis
      - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - ${PGADMIN_PORT}
    env_file:
      - .env
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
