version: "3.8"
services:
  database:
    image: postgres:17.5
    container_name: local_pgdb
    ports:
      - ${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - ${PGADMIN_PORT}
    env_file:
      - .env
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
